fixs pasos ejercicio

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -13,30 +13,41 @@ jobs:
     build:
         runs-on: ubuntu-latest
         outputs:
-            build_status: ${{ steps.build.outputs.resultado == 'SI' && 'success' || 'fail' }}
-        steps:      
-            - name: 'Print GITHUB_OUTPUT path'       
+            build_status: ${{ steps.set_output.outputs.build_status }}
+        steps:
+            - name: Print GITHUB_OUTPUT path       
               run: |
                 echo "var -->> $GITHUB_OUTPUT"
+            
             - name: Build
               id: build
               run: |
                 echo "Building"
-                echo "variable=${{inputs.result}}" >> "$GITHUB_OUTPUT"
+
+            - name: Set output variable
+              id: set_output
+              run: |
+                if [ "${{ inputs.result }}" == "SI" ]; then
+                  echo "build_status=success" >> $GITHUB_OUTPUT
+                else
+                  echo "build_status=fail" >> $GITHUB_OUTPUT
+                fi
 
     deploy:
         runs-on: ubuntu-latest
+        needs: build
         if: ${{ needs.build.outputs.build_status == 'success' }}    
-        steps:      
+        steps:
             - name: Deploy                                     
               run: |
                 echo "Deploying"
+
     rollback:
-      runs-on: ubuntu-latest
-      needs: build
-      if: ${{ needs.build.outputs.build_status != 'success' }}    
-      steps:      
-          - name: Rollback                                     
-            run: |
-              echo "Rollback"
-              exit 1
+        runs-on: ubuntu-latest
+        needs: build
+        if: ${{ needs.build.outputs.build_status == 'fail' }}    
+        steps:
+            - name: Rollback                                     
+              run: |
+                echo "Rollback"
+                exit 1
